services:
  api-rinha2023:
    container_name: rinhaincompleta2023
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5672:5672
    environment:
      - ASPNETCORE_ENVIROMENT=Production
      - MONGO_URL=mongodb://theusdev:Picole123@mongodb-rinha2023:27017/
    depends_on: ["mongo-rinha2023", "redis-cache"]
    networks:
       rinha2023network:

  redis-cache:
    image: redis
    container_name: redis-rinha
    ports:
      - "6379:6379"
    volumes:
      - "redis-rinha2023:/data"
    networks:
      rinha2023network:
       aliases:
         - "redis-rinha2023"


  mongo-rinha2023:
    image: mongo
    container_name: mongo-rinha2023
    restart: always
    environment:
     MONGO_INITDB_ROOT_USERNAME: theusdev
     MONGO_INITDB_ROOT_PASSWORD: Picole123
    ports:
     - 27017:27017
    volumes:
     - "mongo-rinha2023:/data/db"
    networks:
     rinha2023network:
       aliases:
         - "mongodb-rinha2023"

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on: ["mongo-rinha2023", "api-rinha2023"]
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: Picole123
  #     ME_CONFIG_MONGODB_URL: mongodb://theusdev:Picole123@mongo-rinha2023:27017/
  #     ME_CONFIG_BASICAUTH: false



networks:
  rinha2023network:
    driver: bridge

volumes:
  mongo-rinha2023:
    driver: local
  redis-rinha2023:
    driver: local
